[package]
name = "yrteam"
version = "1.0.0"
description = "YR Team Remap ECU Warranty System with Database"
license = "MIT"
readme = "README.md"

[dependencies]
"php/php" = "8.3"

[[command]]
name = "start"
module = "php/php:php"
runner = "wasi"

[command.annotations.wasi]
env = [
    "DB_HOST=db.fr-pari1.bengt.wasmernet.com",
    "DB_PORT=10272",
    "DB_USER=4b26074177e48000ab09d2cdacc3",
    "DB_PASS=06904b26-0741-7964-8000-deb9dc5bf4cb",
    "DB_NAME=YRTeamx",
    "WASMER_ENV=true",
    "PHP_SESSION_SAVE_PATH=/tmp"
]

main-args = ["-S", "0.0.0.0:8080", "-t", "/app"]

[fs]
"/app" = "."
"/tmp" = "tmp"

[net]
bind = ["8080"]

[capabilities.http-client]
enabled = true

[capabilities.http-server]
enabled = true

